# Generated by Django 4.0.5 on 2022-06-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
