# Generated by Django 4.0.5 on 2022-06-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
