# Generated by Django 4.0.5 on 2022-06-06 14:43

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='', validators=[mainapp.validators.validate_file_size]),
        ),
    ]
