# Generated by Django 4.0.5 on 2022-06-06 15:41

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_post_image_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='profile_pictures', validators=[mainapp.validators.validate_file_size]),
        ),
    ]
